######################################################
# ---- (01.)SERVER-SESSION-CONFIGURATION ----
######################################################
server:
    servlet:
        session:
            timeout: 120s
