######################################################
# ---- (01.)LOGGING-CONFIGURATION ----
######################################################
logging:
  config: "classpath:log4j2-spring.xml"

######################################################
# ---- (02.)SERVER-PORT-CONFIGURATION ----
######################################################
server:
  port: 9104

######################################################
# ---- (03.)ACTUATOR-CONFIGURATION ----
######################################################
management:
  endpoints:
    web:
      exposure:
        include: "*"

######################################################
# ---- (04.)EUREKA-CONFIGURATION ----
######################################################
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:9102/eureka/"

######################################################
# ---- (05.)RIBBON-CONFIGURATION ----
######################################################
ribbon:
  ConnectTimeout: 50000
  ReadTimeout: 50000

######################################################
# ---- (06.)HYSTRIX-CONFIGURATION ----
######################################################
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

######################################################
# ---- (07.)SPRING-CONFIGURATION ----
######################################################
spring:
  # ---- (04.01.)SPRING-SECURITY-CONFIGURATION ----
  security:
    user:
      name: "utilisateur"
      password: "mdp"
  # ---- (04.02.)SPRING-DATASOURCE-CONFIGURATION ----
  #datasource:
    #url: "jdbc:mysql://localhost:33306/oauth2db?useSSL=false"
    #username: "oauth2UserName"
    #password: "oauth2Password"
    #driver-class-name: "com.mysql.jdbc.Driver"
    #schema: "classpath:/script/schema.sql"
    #data: "classpath:/script/data.sql"

######################################################
# ---- (08.)SECURITY-CONFIGURATION ----
######################################################
security:
  oauth2:
    client:
      client-id: "acme"
      client-secret: "secret"

