######################################################
# ---- (01.)SERVER-PORT-CONFIGURATION ----
######################################################
#server:
#  port: 9001

######################################################
# ---- (02.)SPRING-CONFIGURATION ----
######################################################
spring:
  # ---- (02.01.)SPRING-DATASOURCE-CONFIGURATION ----
  datasource:
    url: "jdbc:mariadb://localhost:3306/produitdb?createDatabaseIfNotExist=true"
    username: "root"
    password: "tcharou"
    #driverClassName: "com.mysql.cj.jdbc.Driver"
    driverClassName: "org.mariadb.jdbc.Driver"
    sql-script-encoding: UTF-8
    #initialization-mode: always
    #initialize: true
    data: "classpath:import.sql"
  # ---- (02.02.)SPRING-JPA-CONFIGURATION ----
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: "upate"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MariaDB53Dialect"
  # ---- (02.03.)SPRING-H2-CONFIGURATION ----
  #h2:
  #  console:
  #    enabled: true

######################################################
# ---- (03.)ACTUATOR-CONFIGURATION ----
######################################################
management:
  endpoints:
    web:
      exposure:
        include: "*"
    
######################################################
# ---- (04.)EUREKA-CONFIGURATION ----
######################################################
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: "http://localhost:9102/eureka/"

######################################################
# ---- (05.)LOGGING-CONFIGURATION ----
######################################################
logging:
  config: "classpath:log4j2-spring.xml"

######################################################
# ---- (06.)MY CONFIGURATION ----
######################################################
ma-config:
  produitNombreMax: 2
